### PR TITLE
Added some missing units of conversion

### PR DESCRIPTION
**Pull request by martinlindhe**
This patch also renames Velocity to Speed, solves #39

If #39 is not desired, please let me know and I will revert that change.

### CODE REVIEW

**Comment by triplepoint** [comment]
I think I agree that the name Velocity should've been Speed instead, but changing the class name now would be a backwards-compatibility breaking change.

If you'd revert that change here, and maybe submit the Velocity-to-Speed change as a separate PR, I'd let it hang around until the next BC-breaking release (3.0), whenever that happens.  

Regarding the rest of the pull request:
- I'm not sure where you sourced the new conversion factor for lbs to kilograms.  The official NIST definition doesn't have the higher precision: http://physics.nist.gov/Pubs/SP811/appenB9.html#MASSinertia.  Let's stick to the NIST values.
- Similarly the NIST definition of an ounce is given in a direct decimal conversion factor, and not as 1/16th of a lb.  It's probably the same thing, but lets stick to NISTs published numbers where we can.
- time is a tricky topic.  Let's leave out months; the definition is ill-defined and I think it confuses more than it helps to try to define exactly what a "month" means.  I'm ok with adding years.

The rest of it looks good to me.  Thanks again for your contribution.

**Comment by martinlindhe** [comment]
I'm in Europe and haven't looked into the NIST spec:s, but have looked at other sources, like https://en.wikipedia.org/wiki/Conversion_of_units. But sure, let's stick to the NIST stuff.

Updating patch now, thanks for the review!

**Comment by martinlindhe** [comment]
wrt to "Similarly the NIST definition of an ounce is given in a direct decimal conversion factor, and not as 1/16th of a lb. "

yes an ounce is exactly 1/16th of a lb, with the lesser precision it now calculates to 0.9999998236302019, which is slightly off. Looking for another constant from the NIST spec:s

**Comment by martinlindhe** [comment]
something's a bit off in there.

I got it working by using the pound definition and deriving ounce and stone from it, 

one ounce is 1/16 of a pound; https://en.wikipedia.org/wiki/Ounce
one stone is 14 pounds; https://en.wikipedia.org/wiki/Stone_%28unit%29

**Comment by martinlindhe** [comment]
there is no stone definition in NIST afaik (the unit is used in england + ireland)

**Comment by martinlindhe** [comment]
I hope i managed to address all your feedback now!

/m

**Comment by martinlindhe** [comment]
any updates on this?

**Comment by triplepoint** [comment]
Sorry, haven't had a chance to look at this recently.

These changes all look good to me, thanks for your work.

**Comment by martinlindhe** [comment]
great, thank you!

**Pull request merged**
